// Copyright 2020 Working Group Two AS
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

//*
// The voicemail media API allows manipulation of voicemail belonging to a given subscriber.

// @generated by protoc-gen-es v1.3.1 with parameter "target=ts"
// @generated from file wgtwo/voicemail/v0/voicemail.proto (package wgtwo.voicemail.v0, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Duration, Message, proto3, Timestamp } from "@bufbuild/protobuf";
import { PhoneNumber } from "../../common/v0/phonenumber_pb.js";

/**
 * @generated from message wgtwo.voicemail.v0.VoicemailMetadata
 */
export class VoicemailMetadata extends Message<VoicemailMetadata> {
  /**
   * *
   * The ID of the voicemail. (UUID format)
   *
   * @generated from field: string voicemail_id = 1;
   */
  voicemailId = "";

  /**
   * *
   * The MSISDN of the receiver.
   *
   * @generated from field: wgtwo.common.v0.PhoneNumber to = 2;
   */
  to?: PhoneNumber;

  /**
   * *
   * The MSISDN of the sender.
   *
   * @generated from field: wgtwo.common.v0.PhoneNumber from = 3;
   */
  from?: PhoneNumber;

  /**
   * *
   * The length of the voicemail media file in seconds.
   *
   * @generated from field: google.protobuf.Duration duration = 4;
   */
  duration?: Duration;

  /**
   * *
   * Whether or not the voicemail media file has been played.
   *
   * @generated from field: bool played = 5;
   */
  played = false;

  /**
   * *
   * The creation date (epoch in seconds) of the voicemail media file.
   *
   * @generated from field: google.protobuf.Timestamp created = 6;
   */
  created?: Timestamp;

  /**
   * *
   * The expiry date (epoch in seconds) of the voicemail media file.
   * 7 days from the moment the voicemail is created.
   *
   * @generated from field: google.protobuf.Timestamp expires = 7;
   */
  expires?: Timestamp;

  constructor(data?: PartialMessage<VoicemailMetadata>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "wgtwo.voicemail.v0.VoicemailMetadata";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "voicemail_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "to", kind: "message", T: PhoneNumber },
    { no: 3, name: "from", kind: "message", T: PhoneNumber },
    { no: 4, name: "duration", kind: "message", T: Duration },
    { no: 5, name: "played", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "created", kind: "message", T: Timestamp },
    { no: 7, name: "expires", kind: "message", T: Timestamp },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): VoicemailMetadata {
    return new VoicemailMetadata().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): VoicemailMetadata {
    return new VoicemailMetadata().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): VoicemailMetadata {
    return new VoicemailMetadata().fromJsonString(jsonString, options);
  }

  static equals(a: VoicemailMetadata | PlainMessage<VoicemailMetadata> | undefined, b: VoicemailMetadata | PlainMessage<VoicemailMetadata> | undefined): boolean {
    return proto3.util.equals(VoicemailMetadata, a, b);
  }
}

/**
 * *
 * Request object to get metadata for all voicemails.
 *
 * @generated from message wgtwo.voicemail.v0.GetAllVoicemailMetadataRequest
 */
export class GetAllVoicemailMetadataRequest extends Message<GetAllVoicemailMetadataRequest> {
  /**
   * *
   * The MSISDN of the receiver.
   *
   * @generated from field: wgtwo.common.v0.PhoneNumber to = 1;
   */
  to?: PhoneNumber;

  constructor(data?: PartialMessage<GetAllVoicemailMetadataRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "wgtwo.voicemail.v0.GetAllVoicemailMetadataRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "to", kind: "message", T: PhoneNumber },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllVoicemailMetadataRequest {
    return new GetAllVoicemailMetadataRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllVoicemailMetadataRequest {
    return new GetAllVoicemailMetadataRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllVoicemailMetadataRequest {
    return new GetAllVoicemailMetadataRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetAllVoicemailMetadataRequest | PlainMessage<GetAllVoicemailMetadataRequest> | undefined, b: GetAllVoicemailMetadataRequest | PlainMessage<GetAllVoicemailMetadataRequest> | undefined): boolean {
    return proto3.util.equals(GetAllVoicemailMetadataRequest, a, b);
  }
}

/**
 * *
 * Response object for getting metadata for all voicemails.
 *
 * @generated from message wgtwo.voicemail.v0.GetAllVoicemailMetadataResponse
 */
export class GetAllVoicemailMetadataResponse extends Message<GetAllVoicemailMetadataResponse> {
  /**
   * @generated from field: repeated wgtwo.voicemail.v0.VoicemailMetadata metadata = 1;
   */
  metadata: VoicemailMetadata[] = [];

  constructor(data?: PartialMessage<GetAllVoicemailMetadataResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "wgtwo.voicemail.v0.GetAllVoicemailMetadataResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "metadata", kind: "message", T: VoicemailMetadata, repeated: true },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetAllVoicemailMetadataResponse {
    return new GetAllVoicemailMetadataResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetAllVoicemailMetadataResponse {
    return new GetAllVoicemailMetadataResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetAllVoicemailMetadataResponse {
    return new GetAllVoicemailMetadataResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetAllVoicemailMetadataResponse | PlainMessage<GetAllVoicemailMetadataResponse> | undefined, b: GetAllVoicemailMetadataResponse | PlainMessage<GetAllVoicemailMetadataResponse> | undefined): boolean {
    return proto3.util.equals(GetAllVoicemailMetadataResponse, a, b);
  }
}

/**
 * *
 * Request object for getting a voicemail.
 *
 * @generated from message wgtwo.voicemail.v0.GetVoicemailRequest
 */
export class GetVoicemailRequest extends Message<GetVoicemailRequest> {
  /**
   * *
   * The ID of the voicemail. (UUID format)
   *
   * @generated from field: string voicemail_id = 1;
   */
  voicemailId = "";

  constructor(data?: PartialMessage<GetVoicemailRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "wgtwo.voicemail.v0.GetVoicemailRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "voicemail_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetVoicemailRequest {
    return new GetVoicemailRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetVoicemailRequest {
    return new GetVoicemailRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetVoicemailRequest {
    return new GetVoicemailRequest().fromJsonString(jsonString, options);
  }

  static equals(a: GetVoicemailRequest | PlainMessage<GetVoicemailRequest> | undefined, b: GetVoicemailRequest | PlainMessage<GetVoicemailRequest> | undefined): boolean {
    return proto3.util.equals(GetVoicemailRequest, a, b);
  }
}

/**
 * *
 * Response object for getting a voicemail.
 *
 * @generated from message wgtwo.voicemail.v0.GetVoicemailResponse
 */
export class GetVoicemailResponse extends Message<GetVoicemailResponse> {
  /**
   * *
   * The voicemail media file in .wav format.
   *
   * @generated from field: wgtwo.voicemail.v0.VoicemailMetadata metadata = 1;
   */
  metadata?: VoicemailMetadata;

  /**
   * @generated from oneof wgtwo.voicemail.v0.GetVoicemailResponse.bytes
   */
  bytes: {
    /**
     * @generated from field: bytes wav = 2;
     */
    value: Uint8Array;
    case: "wav";
  } | { case: undefined; value?: undefined } = { case: undefined };

  constructor(data?: PartialMessage<GetVoicemailResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "wgtwo.voicemail.v0.GetVoicemailResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "metadata", kind: "message", T: VoicemailMetadata },
    { no: 2, name: "wav", kind: "scalar", T: 12 /* ScalarType.BYTES */, oneof: "bytes" },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): GetVoicemailResponse {
    return new GetVoicemailResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): GetVoicemailResponse {
    return new GetVoicemailResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): GetVoicemailResponse {
    return new GetVoicemailResponse().fromJsonString(jsonString, options);
  }

  static equals(a: GetVoicemailResponse | PlainMessage<GetVoicemailResponse> | undefined, b: GetVoicemailResponse | PlainMessage<GetVoicemailResponse> | undefined): boolean {
    return proto3.util.equals(GetVoicemailResponse, a, b);
  }
}

/**
 * *
 * Request object to mark a voicemail as read.
 *
 * @generated from message wgtwo.voicemail.v0.MarkVoicemailAsReadRequest
 */
export class MarkVoicemailAsReadRequest extends Message<MarkVoicemailAsReadRequest> {
  /**
   * *
   * The ID of the voicemail. (UUID format)
   *
   * @generated from field: string voicemail_id = 1;
   */
  voicemailId = "";

  constructor(data?: PartialMessage<MarkVoicemailAsReadRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "wgtwo.voicemail.v0.MarkVoicemailAsReadRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "voicemail_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MarkVoicemailAsReadRequest {
    return new MarkVoicemailAsReadRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MarkVoicemailAsReadRequest {
    return new MarkVoicemailAsReadRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MarkVoicemailAsReadRequest {
    return new MarkVoicemailAsReadRequest().fromJsonString(jsonString, options);
  }

  static equals(a: MarkVoicemailAsReadRequest | PlainMessage<MarkVoicemailAsReadRequest> | undefined, b: MarkVoicemailAsReadRequest | PlainMessage<MarkVoicemailAsReadRequest> | undefined): boolean {
    return proto3.util.equals(MarkVoicemailAsReadRequest, a, b);
  }
}

/**
 * *
 * Response object for successfully marking a voicemail as read.
 *
 * @generated from message wgtwo.voicemail.v0.MarkVoicemailAsReadResponse
 */
export class MarkVoicemailAsReadResponse extends Message<MarkVoicemailAsReadResponse> {
  constructor(data?: PartialMessage<MarkVoicemailAsReadResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "wgtwo.voicemail.v0.MarkVoicemailAsReadResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): MarkVoicemailAsReadResponse {
    return new MarkVoicemailAsReadResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): MarkVoicemailAsReadResponse {
    return new MarkVoicemailAsReadResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): MarkVoicemailAsReadResponse {
    return new MarkVoicemailAsReadResponse().fromJsonString(jsonString, options);
  }

  static equals(a: MarkVoicemailAsReadResponse | PlainMessage<MarkVoicemailAsReadResponse> | undefined, b: MarkVoicemailAsReadResponse | PlainMessage<MarkVoicemailAsReadResponse> | undefined): boolean {
    return proto3.util.equals(MarkVoicemailAsReadResponse, a, b);
  }
}

/**
 * *
 * Request object to delete a voicemail.
 *
 * @generated from message wgtwo.voicemail.v0.DeleteVoicemailRequest
 */
export class DeleteVoicemailRequest extends Message<DeleteVoicemailRequest> {
  /**
   * *
   * The ID of the voicemail. (UUID format)
   *
   * @generated from field: string voicemail_id = 1;
   */
  voicemailId = "";

  constructor(data?: PartialMessage<DeleteVoicemailRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "wgtwo.voicemail.v0.DeleteVoicemailRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "voicemail_id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteVoicemailRequest {
    return new DeleteVoicemailRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteVoicemailRequest {
    return new DeleteVoicemailRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteVoicemailRequest {
    return new DeleteVoicemailRequest().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteVoicemailRequest | PlainMessage<DeleteVoicemailRequest> | undefined, b: DeleteVoicemailRequest | PlainMessage<DeleteVoicemailRequest> | undefined): boolean {
    return proto3.util.equals(DeleteVoicemailRequest, a, b);
  }
}

/**
 * *
 * Response object for a successful deletion of a voicemail.
 *
 * @generated from message wgtwo.voicemail.v0.DeleteVoicemailResponse
 */
export class DeleteVoicemailResponse extends Message<DeleteVoicemailResponse> {
  constructor(data?: PartialMessage<DeleteVoicemailResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "wgtwo.voicemail.v0.DeleteVoicemailResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): DeleteVoicemailResponse {
    return new DeleteVoicemailResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): DeleteVoicemailResponse {
    return new DeleteVoicemailResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): DeleteVoicemailResponse {
    return new DeleteVoicemailResponse().fromJsonString(jsonString, options);
  }

  static equals(a: DeleteVoicemailResponse | PlainMessage<DeleteVoicemailResponse> | undefined, b: DeleteVoicemailResponse | PlainMessage<DeleteVoicemailResponse> | undefined): boolean {
    return proto3.util.equals(DeleteVoicemailResponse, a, b);
  }
}

/**
 * *
 * Request object to reset the voicemail greeting of a user.
 *
 * @generated from message wgtwo.voicemail.v0.ResetVoicemailGreetingRequest
 */
export class ResetVoicemailGreetingRequest extends Message<ResetVoicemailGreetingRequest> {
  /**
   * *
   * The MSISDN of the subscriber.
   *
   * @generated from field: wgtwo.common.v0.PhoneNumber subscriber = 1;
   */
  subscriber?: PhoneNumber;

  constructor(data?: PartialMessage<ResetVoicemailGreetingRequest>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "wgtwo.voicemail.v0.ResetVoicemailGreetingRequest";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "subscriber", kind: "message", T: PhoneNumber },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResetVoicemailGreetingRequest {
    return new ResetVoicemailGreetingRequest().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResetVoicemailGreetingRequest {
    return new ResetVoicemailGreetingRequest().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResetVoicemailGreetingRequest {
    return new ResetVoicemailGreetingRequest().fromJsonString(jsonString, options);
  }

  static equals(a: ResetVoicemailGreetingRequest | PlainMessage<ResetVoicemailGreetingRequest> | undefined, b: ResetVoicemailGreetingRequest | PlainMessage<ResetVoicemailGreetingRequest> | undefined): boolean {
    return proto3.util.equals(ResetVoicemailGreetingRequest, a, b);
  }
}

/**
 * *
 * Response object for a successful voicemail greeting reset.
 *
 * @generated from message wgtwo.voicemail.v0.ResetVoicemailGreetingResponse
 */
export class ResetVoicemailGreetingResponse extends Message<ResetVoicemailGreetingResponse> {
  constructor(data?: PartialMessage<ResetVoicemailGreetingResponse>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "wgtwo.voicemail.v0.ResetVoicemailGreetingResponse";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ResetVoicemailGreetingResponse {
    return new ResetVoicemailGreetingResponse().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ResetVoicemailGreetingResponse {
    return new ResetVoicemailGreetingResponse().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ResetVoicemailGreetingResponse {
    return new ResetVoicemailGreetingResponse().fromJsonString(jsonString, options);
  }

  static equals(a: ResetVoicemailGreetingResponse | PlainMessage<ResetVoicemailGreetingResponse> | undefined, b: ResetVoicemailGreetingResponse | PlainMessage<ResetVoicemailGreetingResponse> | undefined): boolean {
    return proto3.util.equals(ResetVoicemailGreetingResponse, a, b);
  }
}

